name: CMake_cross_compile_for_ARM_M0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.BUILD_ACTION_PAT }}
    - name: Install gcc
      run: sudo apt install -y gcc-arm-none-eabi    
    - name: Check gcc version
      run: arm-none-eabi-gcc --version
    - name: Check cmake version
      run: cmake --version
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=/usr/bin/arm-none-eabi-gcc .
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Archive BIN
      uses: actions/upload-artifact@v3
      with: 
        name: build-output
        path: build/dali_usb.*
        