name: CMake_cross_compile_for_ARM_M0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install gcc
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '13.3.Rel1'
    - name: Check gcc version
      run: arm-none-eabi-gcc --version
    - name: Check cmake version
      run: cmake --version
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=arm-none-eabi-gcc -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
    - name: Run include what you use
      uses: EmilGedda/include-what-you-use-action@v1.0
      with:
        compilation-database-path: 'build'
        output-format: 'iwyu'
        no-error: 'true'
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Archive BIN
      uses: actions/upload-artifact@v4
      with: 
        name: build-output
        path: build/dali_usb.*
        
